[logger]
level = "info"
messageFormat = "%(asctime)s %(message)s"

[client]
showErrorDetails = true

[server]
# headless = true
port = 8501
maxUploadSize = 20

[browser]
serverAddress = "localhost"
gatherUsageStats = false
serverPort = 8501

[theme]
base = "light"
# font = "sans serif"
